### ISSUE TITLE
Migrate runtime from Cordova to Capacitor

### ISSUE THREAD

**Issue by graphefruit** [graphefruit/Beanconqueror#805]
# Motivation
At least from my outsider's perspective, the Cordova ecosystem is looking more and more abandoned. Most plugins haven't been updated in years, with issues piling up in the respective repositories. This is an issue, as modern mobile platforms evolve rapidly and always require app developers to adapt to new guidelines and restrictions, especially regarding permissions and privacy.

It looks like the Ionic people moved on to create https://capacitorjs.com/, which aims to make native integrations a bit easier while also modernizing the ecosystem (at least that's what Ionic says, see https://ionic.io/resources/articles/capacitor-vs-cordova-modern-hybrid-app-development).

This draft PR is a proof of concept on what a Capacitor migration could look like. Specifically, it demonstrates that existing Cordova plugins can still be used just fine. If the migration works out well, it might be worth it to eventually migrate away from all Cordova plugins, but this is not necessary in the first step.

If you want to take a look at the changes in this PR, I recommend going commit by commit. I try to create isolated, understandable commits. Looking at the commits in order will be much easier than trying to understand the huge diff.

# State of this PR

First things first: **This is currently in the draft/proof of concept stage!**  
This state isn't intended to be mergeable just yet, I just want to be able to get some early feedback.

The second important caveat: **I don't have a Mac and can't test or otherwise work on iOS builds.** I need assistance from someone with access to a Mac and an iPhone.

# To-Do list

This is the current To-Do list I'm working with. As this is still in a very early stage, it will change and things will be added to it.

### First steps
- [x] Get the app to build
- [x] Change scheme/hostname/origin, so no data loss occurs when upgrading from a Cordova build to a Capacitor build

### Test plugin functionality

- [x] Barcode / QR code scanner
- [x] Beanconqueror links
- [x] Camera
- [x] Geolocation
- [x] Bluetooth LE devices
- [x] File Handling (File import/export, Visualizer upload, automatic backup/restore, ...)
- Special HTTP integrations
  - [x] `SanremoYOUDevice`
  - [x] `XeniaDevice`
- [ ] What additional special functionality did I forget?

### General Setup
As I don't have access to a Mac, I can only guess what needs to be done here:
- [x] Initialize the project
```shell
ionic capacitor add ios
npx @capacitor/assets generate --ios
```

### First steps

- [x] Get the app to build
- [x] Check scheme/hostname/origin, so no data loss occurs when upgrading from a Cordova build to a Capacitor build

### Metadata files

- [x] Set up iOS metadata files
  - [x] General iOS metadata files: https://capacitorjs.com/docs/ios/configuration
  - [x] Barcode Scanner Plugin: https://capacitorjs.com/docs/apis/barcode-scanner#ios
  - [x] Camera Plugin: https://capacitorjs.com/docs/apis/camera#ios
  - [x] Geolocation Plugin: https://capacitorjs.com/docs/apis/geolocation#ios
  - [x] Status Bar Plugin: https://capacitorjs.com/docs/apis/status-bar#ios-note
  - [x] Filesystem Plugin: https://capacitorjs.com/docs/apis/filesystem#apple-privacy-manifest-requirements
  - [ ] Possibly more metadata files/plists/...

### Test plugin functionality

- [x] Barcode / QR code scanner
- [x] Beanconqueror links
- [x] Camera
- [x] Geolocation
- [x] Bluetooth LE devices
- [x] File Handling (File import/export, Visualizer upload, automatic backup/restore, ...)
- Special HTTP integrations
  - [x] `SanremoYOUDevice`
  - [x] `XeniaDevice`
- [ ] What additional special functionality did I forget?

### Cordova Plugins to replace in this first step
- [x] `@red-mobile/cordova-plugin-barcodescanner` -> https://capacitorjs.com/docs/apis/barcode-scanner
- [x] `@spoonconsulting/cordova-plugin-telerik-imagepicker`
  - Is https://capacitorjs.com/docs/apis/camera#pickimages enough for this?
- [x] `cordova-clipboard` -> https://capacitorjs.com/docs/apis/clipboard
- [/] `cordova-plugin-android-permissions`
  - Used directly and as a dependency of other plugins
  -> Permissions need to stay cause the new capacitor plugins doesn't allow the possibility to check Bluetooth e.g.
- [x] `cordova-plugin-androidx-adapter` -> Not required in Capacitor
- [x] `cordova-plugin-androidx` -> Not required in Capacitor
- [x] `cordova-plugin-app-version` -> https://capacitorjs.com/docs/apis/app#getinfo
- [x] `cordova-plugin-appminimize` -> https://capacitorjs.com/docs/apis/app#minimizeapp
- [x] `cordova-plugin-camera` -> https://capacitorjs.com/docs/apis/camera
- [x] `cordova-plugin-device` -> https://capacitorjs.com/docs/apis/device
- [x] `cordova-plugin-geolocation` -> https://capacitorjs.com/docs/apis/geolocation
- [x] `cordova-plugin-globalization`
  - Deprecated, should also be removed if we stay on Cordova
  - Use Browser API: https://402.ecma-international.org/1.0/
  - See https://cordova.apache.org/news/2017/11/20/migrate-from-cordova-globalization-plugin.html
- [x] `cordova-plugin-inappbrowser`
  - Doesn't seem to be used anyway, all links open in external browser
  - Replace with `window.open()`? -> Not possible on Android because it will overwrite the own app.
- [x] `cordova-plugin-ionic-keyboard` -> https://capacitorjs.com/docs/apis/keyboard
- [x] `cordova-plugin-ionic-webview`
  - Unused in Capacitor. Not getting pulled in, verified by running `npx cap ls`
- [x] `cordova-plugin-screen-orientation`
  - Was unused anyway, DOM APIs for this are used instead
- [x] `cordova-plugin-statusbar` -> https://capacitorjs.com/docs/apis/status-bar
- [x] `cordova-plugin-vibration` -> https://capacitorjs.com/docs/apis/haptics
- [x] `cordova-plugin-file` -> https://capacitorjs.com/docs/apis/filesystem
  - **Important!** This plugin is broken at least on Android in conjunction with Capacitor, so it must be replaced
- [x] `cordova-plugin-file-transfer`
  - **Important!** Must be removed to be able to remove  `cordova-plugin-file`
- [x] `cordova-plugin-advanced-http` -> https://capacitorjs.com/docs/apis/http
  - **Important!** Must be removed to be able to remove  `cordova-plugin-file`
- [x] `cordova-plugin-filepath`
  - Used on Android only
- [x] `cordova-plugin-x-socialsharing`
- If possible this should be removed to be able to lose `es6-promise-plugin` as well
- [x] `es6-promise-plugin`
  - Is this even used in the Capacitor webview, even though it's a dependency of `cordova-plugin-x-socialsharing`? It shouldn't be needed anyway, verify!

### Cordova Plugins to specifically _not_ replace in this first step
- `cordova-plugin-ble-central`
  - Way too complex to attempt to replace this in the first step. Also, I don't have any Bluetooth devices to test 
- [x] `ionic-plugin-deeplinks`
  - Replaced by native capacitor

### Cordova Plugins to still decide the fate of
- [x] `cordova-plugin-3dtouch`
  - Used on iOS only, I don't know what this is for
  -> Made it native directly.
- [x] **File handling and file choosers** (Probably not necessary to migrate in the first step)
  - [x] `cordova-plugin-filechooser`
    - Used on Android only
  - [x] `cordova-plugin-filepicker`
    - Used on iOS only
- [/] `cordova-plugin-health`
 -> Actually not possible, the capacitor-healthkit not supports capacitor 6.X
- [x] `cordova-plugin-insomnia`
- [X] `cordova-plugin-nativestorage`
- [ ] `cordova-sqlite-storage`
- [ ] `skwas-cordova-plugin-datetimepicker`

## General
- [x] Rewrite most of the file system handling to clean it up, mainly:
  - [x] `UIFileHelper`
  - [x] `UIExportImportHelper`
    - This could be cleaner, but it's already a lot better and works in my testing. More refactoring can be done at a later point
- [ ] Review all `TODO Capacitor migration` I left during the migration
- [ ] A lot of testing when the PR gets more mature to make sure nothing breaks
- [x] Add a proof of concept for using custom native code to do stuff we couldn't do before
  - #806 

Explicit Check:
- [x] Check if bluetooth permissions need to be added in android manifest

Extra todo:
- [x] Update to Ionic 8
- [x] Update to latest Angular
- [x] Somehow a build script for iOS / Android.
Specially for Android referencing: ionic cordova build --prod --release (--release was the bundled version)

**Comment by RagingCactus** [comment]
I'll take a look at the Android permissions for Bluetooth in the manifest. However, I can't test the connection as I have no BLE coffee devices.

**Comment by graphefruit** [comment]
We've done a lot of tests, and even found some beta testers.
Specialy the new import/export worked.
QR-Code Scanner
NFC-Tag Scanner
Images adding
Brew-graph savings etc.

Great job @RagingCactus !
I gonna close this ticket now
